
# Project ID: This must be the first line
project_id = "wmwwjdkjybtwqzrqchfh"

[api]
# Port to use for the API URL.
port = 54321
# Enable GraphQL
enabled = false

[db]
# Port to use for the local database URL.
port = 54322

[functions]
[functions.coingecko-rates]
verify_jwt = false
[functions.log-event]
verify_jwt = false

[inbucket]
# Port to use for the inbucket web interface URL.
port = 54324

[storage]
# The maximum file size allowed (e.g. "5MB", "500KB").
file_size_limit = "50MiB"

[studio]
# Port to use for Supabase Studio.
port = 54323
