// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmwwjdkjybtwqzrqchfh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indtd3dqZGtqeWJ0d3F6cnFjaGZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MjUyNzEsImV4cCI6MjA2MDMwMTI3MX0.kVbdTSjKsRgOGbKNUKrKIigrMrYhf9pdEcXTCt87kAs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);